Feature/week2 compose
NOW-SOPT-ANDROID/sangwook-woo pull request #6
Opened 2024-04-16 11:02 UTC by Sangwook123

## 📌 PR 요약

🌱 작업한 내용
- 필수과제
- xml과 동일하게 구현

🌱 PR 포인트
- feature모듈 분리
- compose navi 활용

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨

https://github.com/NOW-SOPT-ANDROID/sangwook-woo/assets/113014331/e223f5b2-b906-4a05-9936-773560dd0381

부바람|

## 📮 관련 이슈
- Resolved: #이슈번호

2024-04-20 11:46 UTC, jihyunniiii reviewed
오빠 몰공 그만해

2024-04-20 11:46 UTC, jihyunniiii commented on build-logic/convention/build.gradle.kts
배지현 우상욱의 코드를 보고 드디어 멀티 모듈을 어느 정도 이해하다 ㅋㅋ
ㄱㅅ 합니다

2024-04-20 11:46 UTC, jihyunniiii commented on core/common/src/androidTest/java/com/sopt/common/EncryptTest.kt
나중에 테스트 코드 미미나 제발 열어주세요

2024-04-21 12:54 UTC, twogarlic reviewed
수고하셨습니다 !!

2024-04-21 13:00 UTC, twogarlic commented on core/data/src/main/java/org/sopt/data/repository/UserDataRepositoryImpl.kt
> +    override fun getUserData() = userPreferencesDataSource.userData.map {
여기서 반환된 데이터는 어떻게 사용되나요?

2024-04-21 13:01 UTC, twogarlic commented on core/common/src/main/java/org/sopt/common/security/SecurityUtil.kt
> +    private val provider = "AndroidKeyStore"
이 친구의 역할은 뭔가요?

2024-04-21 13:16 UTC, 0se0 reviewed
수고하셨습니다!👍🏻👍🏻👍🏻👍🏻

2024-04-21 13:16 UTC, 0se0 commented on build-logic/convention/src/main/java/UnitTestPlugin.kt
> +                "testImplementation"(libs.findLibrary("mockito").get())
오 모키토 처음 봤어요

2024-04-21 13:16 UTC, 0se0 commented on feature/home/src/main/java/org/sopt/home/HomeFriendContainer.kt
> +            )
오 이렇게 동적으로 조절하는군여

2024-04-21 13:16 UTC, 0se0 commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +    onClickDialogNegativeButton: () -> Unit = {},
컴포즈에선 이렇게 매개변수를 많이 보낼 수 밖에 없는건가요?

2024-04-21 13:16 UTC, 0se0 commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +                placeholder = "검색어를 입력해주세요"
우아 검색!!!!

2024-04-27 05:48 UTC, 2hyunjinn commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +                placeholder = "검색어를 입력해주세요"
혼자 잘하네 ㅋㅋ 짱난당

2024-04-29 03:30 UTC, l2hyunwoo commented
@Sangwook123 모듈 추가 관련해서 - 멀티 모듈을 과제에서 진행하는 것은 좋은데 리뷰어 입장에서는 변경된 파일수가 너무 많아서 리뷰하기가 너무 힘듭니다. 

- 최소한 [모듈 그래프](https://github.com/JakeWharton/SdkSearch/blob/master/gradle/projectDependencyGraph.gradle) 정도는 before, after 비교할 수 있게 올려주시면 좋을 것 같습니다.
- 모듈 추가시 필요 없는 파일들은 삭제 부탁드립니다.

2024-04-29 04:08 UTC, l2hyunwoo requested changes
리뷰 확인 부탁드립니다. 우선 논의해봐야할 게 좀 많을 것 같네요.

2024-04-29 04:08 UTC, l2hyunwoo commented on build-logic/convention/build.gradle.kts
> +        }
sopt.plugin.test와 sopt.android.test는 겉보기에 비슷한 기능으로 동작할 수 있을 것 같다 생각이 드네요. Android Test 플러그인은 sopt.plugin.android.test로 바꿔보는건 어떨까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on build-logic/convention/src/main/java/AndroidTestPlugin.kt
> +}
android test 같은 경우 instrumentation runner 설정해야 하는 것으로 알고 있습니다. 그리고 context때문에 android test 사용하는 거라면 [robolectric](https://robolectric.org/) 사용하면 되니까 그거 참고해서 사용해보시면 좋을 것 같아요.

2024-04-29 04:08 UTC, l2hyunwoo commented on build-logic/convention/src/main/java/HiltPlugin.kt
테스트 라이브러리인데 implementation으로 참조해야하는 이유가 있나요?

2024-04-29 04:08 UTC, l2hyunwoo commented on core/common/build.gradle.kts
> +}
컨벤션 플러그인 좀 더 잘 활용해보면 여기 코드도 많이 줄일 수 있을 것 같습니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on core/data/src/test/java/org/sopt/data/ExampleUnitTest.kt
미사용 파일들은 삭제해주시면 좋을 것 같습니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on core/common/src/androidTest/java/com/sopt/common/EncryptTest.kt
이거 굳이 android test에서 안만드셔도 됩니다. 제가 SOPT앱에서 테스트 했을때에는 unit test 단에서 충분히 해결가능했던 테스트였습니다. [이거](https://github.com/sopt-makers/sopt-android/tree/develop/app/src/test/java/org/sopt/official/datastore) 참고해보세요.

2024-04-29 04:08 UTC, l2hyunwoo commented on core/datastore/src/main/java/org/sopt/datastore/source/UserPreferencesDataSource.kt
> +        }
이러면 catch, throw를 하는 의도가 무엇인가요?

2024-04-29 04:08 UTC, l2hyunwoo commented on core/designsystem/src/main/java/org/sopt/designsystem/component/dialog/SoptAlertDialog.kt
> +        onDismissRequest = { onClickNegative() },
```suggestion
        onDismissRequest = onClickNegative,
```

취향차이인데 이렇게 쓸 수도 있습니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on core/domain-test/src/test/java/org/sopt/domain_test/UseCaseTest.kt
안드로이드 폴더 네이밍 컨벤션에서는 underscore를 지양합니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on core/domain/build.gradle.kts
> +    implementation(libs.hilt.core)
javax.inject 라이브러리 추가해주는 것으로 갈음할 수 있습니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on core/domain/build.gradle.kts
> +    implementation(projects.core.model)
core model 모듈 코틀린 모듈인가요?

2024-04-29 04:08 UTC, l2hyunwoo commented on core/domain/src/main/java/org/sopt/domain/usecase/GetSoptUseCase.kt
> +            }
- mapLatest와 flatMapLatest중에서 flatMapLatest를 선택하신 이유가 있을가요?
- flatMapMerge, flatMapConcat, flatMapLatest의 차이는 무엇일까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on core/ui/src/main/java/org/sopt/ui/orbit/OrbitExt.kt
> +import org.orbitmvi.orbit.syntax.simple.reduce
이건 순전히 질문) orbit 사용하시는 이유가 있을까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/AddFriendBottomSheet.kt
> +) {
안드로이드(컴포즈) 코딩 컨벤션인데 참고만 하세요.

- required parameter는 optional parameter 위에 있어야 합니다.
- Modifier는 모든 optional parameter 중 가장 상위에 있어야 합니다.

그렇다면 아래와 같이 바꿀 수 있습니다.

```suggestion
fun AddFriendBottomSheet(
    sheetState: SheetState,
    onClickSave: () -> Unit,
    onNameValueChange: (String) -> Unit,
    onHobbyValueChange: (String) -> Unit,
    state: HomeState,
    modifier: Modifier = Modifier,
    onDismissRequest: () -> Unit = {},
) {
```

그리고 state가 많이 주입되고 있는데, state 호이스팅을 이렇게 하는 이유가 있을까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/AddFriendBottomSheet.kt
> +        Spacer(modifier = Modifier.height(40.dp))
이렇게 spacer가 주어져있으면 Column의 verticalArrangement를 `Arrangement.spacedBy(40.dp)` 사용해보는 것도 고려할 것 같습니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeContract.kt
> +)
이렇게 데이터클래스가 만들어지면 잠재적으로 발생할 수 있는 문제점은 무엇이 있을까요?

hint) Compose Stability

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeFriendContainer.kt
> +    painter: Painter = painterResource(R.drawable.ic_launcher_background),
Painter도 Compose Stability에 걸립니다....

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +    val state = viewModel.collectAsState().value
- value를 사용해서 구독하는 것보다 by(getValue) 사용해보는 것이 가독성에 더 좋을 것 같습니다.
- 아래와 같이 state 구독함수를 변경하면 어떤 점이 달라질까요?

```suggestion
    val state by viewModel.collectAsStateWithLifecycle()
```

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +    val sheetState = rememberModalBottomSheetState()
state hoisting을 최상위 루트에까지 두어야 하는 이유가 있을까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +                    ) + state.friendList,
컴포즈 뷰 내에서 연산 로직을 두는 것보다 외부에서 연산을 시키는 것이 더 좋을 것 같습니다. 리컴포지션시 해당 로직이 반복적으로 호출될것이기 때문이죠.

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +    private val soptRepository: SoptRepository,
UseCase가 주입되는데 repository를 따로 주입하는 이유가 있을까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +        getSoptUseCase(param = GetSoptUseCase.Param(state.query)).collect {
`GetSoptUseCase.Param(state.query)`

query를 해당 클래스로 wrapping한 이유가 따로 존재할까요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +        val friend = Friend(null, state.savingName, state.savingHobby)
- 가독성을 위해서 named argument를 적어주시면 감사하겠습니다.
- id 값에 null을 넣는 이유가 있나요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/home/src/test/java/org/sopt/home/ExampleUnitTest.kt
필요없는 파일 삭제 부탁드립니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/login/LoginContract.kt
> +    fun checkRegister() = registeredId.isBlank() || registeredPassword.isBlank()
해당 검증 결과는 상태로 저장할 수 있습니다.

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/login/LoginContract.kt
> +    fun matchesUserInfo(id: String, password: String) =
이것 역시

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/model/UserModel.kt
> +) : Parcelable
UserModel을 Parcelize로 감싼 이유가 있을까요? compose-navigation에서는 아직 Parcelable 타입을 argument로 넘기기 힘든걸로 알고 있는데요

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/navigator/MainNavigator.kt
> +    }
:+1:

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/navigator/MainScreen.kt
> +@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
innerPadding을 사용한 케이스와 안 사용한 케이스에서 UI가 어떻게 달라지는 지 알고 계신가요?

2024-04-29 04:08 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/navigator/MainScreen.kt
> +import okhttp3.internal.toImmutableList
immutableList는 okhttp가 아닌 kotlinx.immutable.collection 라이브러리를 사용하시면 됩니다.

2024-04-29 09:50 UTC, Sangwook123 commented on core/common/src/androidTest/java/com/sopt/common/EncryptTest.kt
저도 테스트 코드 처음ㅇㅣ에요 ㅜ

2024-04-29 09:51 UTC, Sangwook123 commented on core/data/src/main/java/org/sopt/data/repository/UserDataRepositoryImpl.kt
> +    override fun getUserData() = userPreferencesDataSource.userData.map {
유저정보 조회에 사용됩니다 !

2024-04-29 09:53 UTC, Sangwook123 commented on core/common/src/main/java/org/sopt/common/security/SecurityUtil.kt
> +    private val provider = "AndroidKeyStore"
데이터 암복호화에 사용됩니다. datastore에 저장되는 정보들을 암호화 해주기위해 사용중입니다.

2024-04-29 09:53 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +    onClickDialogNegativeButton: () -> Unit = {},
해당 화면에서 처리해 주어야 할 이벤트들이 많아서 지금처럼 작성했습니다.

2024-04-29 09:54 UTC, Sangwook123 commented on build-logic/convention/build.gradle.kts
> +        }
동의합니다! 좀 더 직관적인 네이밍에 대해서 항상 더 생각해보겠습니다 ! 

아울러 앞서 말씀해주신 부분들 고민해봤습니다. 고려하지 못하고 있던 부분인데 집어주셔서 감사합니다 ! 원활한 리뷰를 위해서 모듈 추가하는 부분들은 별도의 PR로 분리하고 구현 내용만 과제 PR로 올리는 방식 생각중입니다. 또한 모듈그래프도 비교할 수 있도록 추가해두겠습니다.

2024-04-29 09:56 UTC, Sangwook123 commented on build-logic/convention/src/main/java/AndroidTestPlugin.kt
> +}
android library convention에서 instrumentation runner를 따로 설정해주고 있었습니다만, android test 플러그인으로 이관하는 편이 좋을것 같습니다. robolectric 활용해서 unit test로 전환해보겠습니다. 감사합니다 !!

2024-04-29 09:58 UTC, Sangwook123 commented on build-logic/convention/src/main/java/HiltPlugin.kt
테스트를 위한 mock datastore를 testInstallIn하기 위해서 implementation으로 참조 해주었습니다. 결론적으론 unit test가 어려워서 일단 보류해두었습니다 🥲

2024-04-29 09:59 UTC, Sangwook123 commented on core/common/src/androidTest/java/com/sopt/common/EncryptTest.kt
와.. 사실 이 암호화 테스트를 굳이 android test에서 해야하나 고민이 많았었는데, 너무 감사드립니다 !! 참고해서 적용해보도록 하겠습니다 !

2024-04-29 10:00 UTC, Sangwook123 commented on core/datastore/src/main/java/org/sopt/datastore/source/UserPreferencesDataSource.kt
> +        }
나중에 처리해주어야지.. 하고 예외를 던지기만하고 있었네요.. 수정하겠습니다

2024-04-29 10:01 UTC, Sangwook123 commented on core/domain-test/src/test/java/org/sopt/domain_test/UseCaseTest.kt
네이밍 컨벤션도 잘 고려하겠습니다 감사합니다!!

2024-04-29 10:02 UTC, Sangwook123 commented on core/domain/build.gradle.kts
> +    implementation(projects.core.model)
넵 코틀린 모듈입니다 !

2024-04-29 10:08 UTC, Sangwook123 commented on core/domain/src/main/java/org/sopt/domain/usecase/GetSoptUseCase.kt
> +            }
음.. 동적인 입력값중 최신입력값에 해당하는 결과를 받아오기 위해서 사용했는데 다시보니까 이미 받아온 데이터를 넘기기만 하고있네요 🥲🥲  flatmaplatest는 출력단이 아니라 입력단에서 처리해주는게 맞을것 같습니다. 수정하겠습니다!

아울러 flatMapMerge와 flatMapConcat은 사용해본적은 없지만 전자는 데이터를 병렬적으로 생산하고, 후자는 동기적?으로 생산한다. 정도로 이해하고 있습니다. 이후에 flow 연산자들에 대해서 좀더 공부해보겠습니다. 감사합니다 !

2024-04-29 10:09 UTC, Sangwook123 commented on core/ui/src/main/java/org/sopt/ui/orbit/OrbitExt.kt
> +import org.orbitmvi.orbit.syntax.simple.reduce
특별한 이유는 없습니다! orbit사용해본 적이 없어서 한번 해보고 싶어서 적용해봤습니다.

2024-04-29 10:13 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/AddFriendBottomSheet.kt
> +) {
컴포즈 지식이 짧아서 컨벤션도 잘 모르고 있었는데, 감사합니다 ! 

그리고 상태 호이스팅에 아직 익숙하지 않아서 무작정 끌어올리기만 하고 있었습니다. 일종의 패턴 중독이었던 것 같습니다. 좀 더 재사용성과 적합성등을 고려해서 불필요한 호이스팅은 피하도록 하겠습니다 !

2024-04-29 10:15 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeContract.kt
> +)
List타입은 컴포즈에서 stable로 간주되지 않기때문에 상태 안정성을 보장하지 못할 것같습니다. ImmutableList로 변경하겠습니다 ! 그리고 Pair같은 경우에는 현재 제네릭 타입이 stable하기 때문에 stable로 간주 될 것 같긴한데.. 이 부분은 좀 더 찾아보겠습니다.

2024-04-29 10:15 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeFriendContainer.kt
> +    painter: Painter = painterResource(R.drawable.ic_launcher_background),
하하... 수정하겠습니다 🥲

2024-04-29 11:51 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +    val state = viewModel.collectAsState().value
composable의 lifecycle에 맞게 데이터 수집을 관리해주기 때문에 보다 효율적일 것 같습니다. 감사합니다 !!

2024-04-29 11:51 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +    val sheetState = rememberModalBottomSheetState()
딱히 없다고 생각합니다🥲 보다 적합하게 수정하겠습니다 !

2024-04-29 11:52 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +                    ) + state.friendList,
아 그렇겠네요 ! 고려하지 못하고 있던 부분이었는데, 유용한 팁 감사드립니다 !

2024-04-29 11:52 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +    private val soptRepository: SoptRepository,
단순 매핑형식으로 사용되는 usecase들을 경계하고 있어서 필요한 부분만 usecase를 만들어 쓰고자 했는데, 이부분은 좀 더 일관성있게 고쳐보겠습니다.

2024-04-29 11:54 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +        getSoptUseCase(param = GetSoptUseCase.Param(state.query)).collect {
개인적으로 선호하는 코딩 스타일입니다. usecase에 전달되는 입력값들을 한눈에 명확하게 확인할 수 있고 기능 확장에도 용이하다 생각해서 선호하게 되었습니다.

2024-04-29 11:55 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +        val friend = Friend(null, state.savingName, state.savingHobby)
primary key는 자동생성되기 때문에 null을 넣어주었는데, 지금보니 데이터 클래스 기본생성자를 사용하는 편이 나아보입니다 !

2024-04-29 11:55 UTC, Sangwook123 commented on feature/main/src/main/java/org/sopt/main/model/UserModel.kt
> +) : Parcelable
xml과제 파일을 그대로 복사해오면서 만들어졌는데, parcelable을 사용하고 있진 않습니다. 이 부분도 수정하겠습니다 !

2024-04-29 11:56 UTC, Sangwook123 commented on feature/main/src/main/java/org/sopt/main/navigator/MainScreen.kt
> +@SuppressLint("UnusedMaterial3ScaffoldPaddingParameter")
innerPadding을 적용해주어야할 것 같습니다. 지금의 경우 content영역에 바텀바의 크기가 고려되지 않아서 아래부분이 짤릴 것 같습니다.

2024-04-30 05:40 UTC, l2hyunwoo approved these changes
빠르군요

2024-04-30 05:40 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
>                  .collect {
collect vs collectLatest 차이 한번 조사해보시겠아요?

2024-05-01 03:09 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
>                  .collect {
collect랑 다르게 collectLatest는 구독중인 flow에서 새로운 값이 방출 될 경우 블럭 내부의 작업을 즉시 취소하고 새로운 값으로 재시작합니다. collectLatest를 활용해서 좀 더 최적화 할 수 있을 것 같습니다. 감사합니다 !

2024-05-01 04:15 UTC, merged