Feature/week4 compose
NOW-SOPT-ANDROID/sangwook-woo pull request #8
Opened 2024-05-03 09:45 UTC by Sangwook123

## 📌 PR 요약

🌱 작업한 내용
- 4주차 과제

🌱 PR 포인트
- 필수

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|
before
![week2](https://github.com/NOW-SOPT-ANDROID/sangwook-woo/assets/113014331/c453c285-f1a5-4cbd-b51b-a05a7554a580)
after
![week4](https://github.com/NOW-SOPT-ANDROID/sangwook-woo/assets/113014331/fa4daa80-e860-4f16-86a7-f0612e09d5d2)

https://github.com/NOW-SOPT-ANDROID/sangwook-woo/assets/113014331/d8d048ac-23fa-445a-86f2-8e96950f3a7e

## 📮 관련 이슈
- Resolved: #이슈번호

2024-05-03 16:06 UTC, l2hyunwoo requested changes
수고하셨습니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/data/build.gradle.kts
> +    implementation(libs.androidx.paging)
data plugin에 추가되었는데 굳이 한번더 추가한 이유가 있을까요?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/data/src/main/java/org/sopt/data/paging/UserPagingSource.kt
> +    }
- getRefreshKey를 위와 같이 구현한 이유가 무엇일까요?
- anchorPosition이 가지는 값과 전달해주어야 하는 키는 어떤 연관성을 지닐까요?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/data/src/main/java/org/sopt/data/paging/UserPagingSource.kt
> +            val currentPage = params.key ?: 1
이건 저도 별로 신경을 안쓰는 부분이긴 한데 API에 따라서 시작 값이 1로 시작하는 경우가 있고 0으로 시작하는 경우도 있습니다. 케이스마다 initial 값이 달라서 헷갈릴 수 있으니 상수화해서 값 사용하는게 좋을 것 같습니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/data/src/main/java/org/sopt/data/repository/AuthRepositoryImpl.kt
> +        }
mapCatching, recoverCatching 살펴보세요.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/data/src/main/java/org/sopt/data/repository/AuthRepositoryImpl.kt
> +        return handleResult(result)
Result 객체는 여러번의 체이닝을 통해서 값을 업데이트 시킬 수 있는 특이한 형태의 객체입니다. 이점을 활용해보는건 어떨지 제안드립니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/data/src/main/java/org/sopt/data/repository/UserRepositoryImpl.kt
> +        return Pager(PagingConfig(6, 2)) {
6, 2가 각각 어떤걸 상징하죠?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/domain/src/main/java/org/sopt/domain/usecase/ValidatePasswordUseCase.kt
> +        )
👍🏻

2024-05-03 16:06 UTC, l2hyunwoo commented on core/domain/src/main/java/org/sopt/domain/repo/AuthRepository.kt
> +    suspend fun getUserinfo(): Result<Member?>
성공시에도 Member가 null로 떨어지는 경우가 있나요? 그런 경우에는 성공값으로 내려주기보단 에러로 래핑하는게 좀 더 낫지 않을까 하는 생각이 듭니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/domain/src/main/java/org/sopt/domain/repo/AuthRepository.kt
> +    suspend fun getUserinfo(): Result<Member?>
물론 실제 상황이라면 기획/디자인과 추가로 이야기를 해봐야하겠지만

이런 케이스가 있다는 것을 생각이 되신다면, null 타입은 들어가지 않게 하고 null에 해당되는 케이스는 throw해서 받아올 것 같네요.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/domain/src/main/java/org/sopt/domain/repo/AuthRepository.kt
> +    suspend fun postSignup(member: Member, pw: String): Result<Base<Nothing>>
Base<Nothing> 타입을 사용하시는 이유가 궁금하네요. 타입 설계를 이렇게 하는 이유가 있을까요?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/model/src/main/java/org/sopt/model/ValidateResult.kt
> +fun getResult(isValid: Boolean) = if (isValid) ValidateResult.Success else ValidateResult.Error
저라면 sealed class 내부에 공통 메서드로 구현할 것 같습니다...UseCase에서 getResult라는 네이밍이 왜 있었는지, 왜 갑자기 ValidationResult라는 값을 리턴하는지 이유를 몰랐는데 여기 봐서야 그 이유를 알 수 있었네요.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/model/src/main/java/org/sopt/model/Base.kt
> +)
이걸 도메인/비즈니스 단에서 그대로 사용하시는 이유가 있으신가요?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/network/di/ApiModule.kt
> +        retrofit.create(ReqresApi::class.java)
```suggestion
    @Provides
    @Singleton
    fun provideAuthService(@Auth retrofit: Retrofit): AuthApi =
        retrofit.create()

    @Provides
    @Singleton
    fun provideReqresService(@Reqres retrofit: Retrofit): ReqresApi =
        retrofit.create()
```

create에 타입 기반 생성 로직 있어서 이렇게만 해도 생성될거에요.

2024-05-03 16:06 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/network/interceptor/AuthInterceptor.kt
> +        ).addHeader("Accept-Encoding", "identity").build()
이 값 추가하는 이유가 있을까요?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/network/interceptor/AuthInterceptor.kt
> +        runBlocking { if (memberId != null) userPreferencesDataSource.setMemberId(memberId) }
memberId가 Location 키를 통해서 내려오게 되는건가요?

2024-05-03 16:06 UTC, l2hyunwoo commented on core/network/src/main/java/org/sopt/network/model/response/base/ApiError.kt
> +)
```suggestion
@Serializable
data class ApiError(
    val code: Int,
    val message: String,
) : Exception()
```

이런걸 상속받아서 Custom Exception 형태로 제작하면 runCatchong에서 해당 Error(Excpetion)을 throw할 수 있습니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeScreen.kt
> +            { index ->
```suggestion
            items(postItem.itemCount) { index ->
```

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +    val userState: StateFlow<PagingData<ReqresUser>> = _userState.asStateFlow()
PagingData를 StateFlow로 저장해두는 이유가 있을까요?

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/main/src/main/java/org/sopt/main/login/LoginViewModel.kt
> +            Log.e("throwable", it.toString())
Failure 상황에서도 로직 추가가 필요할 것 같습니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/mypage/src/main/java/org/sopt/mypage/modifypassword/ModifyPasswordScreen.kt
> +    navigateMypage: () -> Unit,
```suggestion
fun ModifyPasswordRoute(
    navigateMypage: () -> Unit,
    modifier: Modifier = Modifier,
    viewModel: ModifyPasswordViewModel = hiltViewModel(),
```

- 모든 선택 패러미터는 필수 패러미터 아래에 있는 것을 권장합니다 (Compose API GuideLine 기반)

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/mypage/src/main/java/org/sopt/mypage/modifypassword/ModifyPasswordScreen.kt
> +                    )
👍🏻

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/mypage/src/main/java/org/sopt/mypage/modifypassword/ModifyPasswordScreen.kt
> +        onValueChangeNewPasswordVerification = viewModel::updateNewPasswordVerification
오 메서드 레퍼런스 사용 굿입니다.

2024-05-03 16:06 UTC, l2hyunwoo commented on feature/mypage/src/main/java/org/sopt/mypage/modifypassword/ModifyPasswordViewModel.kt
> +                }
validation 로직이 뷰모델에서 일어나야할 로직일까요?

2024-05-05 13:46 UTC, 0se0 reviewed
수고하셨습니다!

2024-05-05 13:46 UTC, 0se0 commented on feature/main/src/main/java/org/sopt/main/navigator/MainScreen.kt
> +                                launchSingleTop = true
`launchSingleTop = true` 부분은 어떤 기능을 하는 지 궁금합니다!

2024-05-05 14:09 UTC, twogarlic reviewed
수고하셨습니다!

2024-05-05 14:17 UTC, t1nm1ksun commented
고생하셨습니다!

2024-05-07 11:57 UTC, t1nm1ksun commented on core/datastore/src/main/java/org/sopt/datastore/source/UserPreferencesDataSource.kt
>      suspend fun setUserData(user: UserData) {
다른 메서드 없이 copy를 이용해서 set 과 delete를 구현해야 되는건가요?

2024-05-08 04:10 UTC, Sangwook123 reviewed
@l2hyunwoo 꼼꼼한 리뷰 감사드립니다 ! 타입 설계와 예외 처리에 관련해서 충분히 고민해보고 수정해서 다시 리뷰요청 드리겠습니다 !

2024-05-08 04:10 UTC, Sangwook123 commented on core/data/src/main/java/org/sopt/data/paging/UserPagingSource.kt
> +    }
getRefreshKey는 데이터를 새로고침 할때 요청할 키 값을 반환하는 함수이고, 저는 이를 현재 위치를 반환하면 되는 것으로 이해를 했기때문에 지금처럼 작성 했습니다만, 다시 알아보니 state.anchorPosition은 현재 페이지에 대한 키값을 직접적으로 나타내진 않습니다.

closestPageToPosition을 사용해서 가장 가까운 페이지의 키 값을 구해주면 될 것 같습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/data/src/main/java/org/sopt/data/repository/AuthRepositoryImpl.kt
> +        return handleResult(result)
넵 ! 좀 더 Result의 특성에 맞게 구현해보겠습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/data/src/main/java/org/sopt/data/repository/UserRepositoryImpl.kt
> +        return Pager(PagingConfig(6, 2)) {
pageSize와 prefetchDistance입니다. named argument와 상수화 좀 더 습관화 하겠습니다. 🥲

2024-05-08 04:10 UTC, Sangwook123 commented on core/domain/src/main/java/org/sopt/domain/repo/AuthRepository.kt
> +    suspend fun postSignup(member: Member, pw: String): Result<Base<Nothing>>
ui와 data에서 코어로 사용되는 형식으로 좀 더 유연하게 설계하고 싶었습니다. 다만 서버로부터의 status 코드는 ui가 알아야 할 정보는 아닌 것 같다고 생각해서 이 부분은 좀 더 고민해보겠습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/model/src/main/java/org/sopt/model/Base.kt
> +)
ui와 data에서 코어로 사용되는 형식으로 좀 더 유연하게 설계하고 싶었습니다. 다만 서버로부터의 status 코드는 ui가 알아야 할 정보는 아닌 것 같다고 생각해서 이 부분은 좀 더 고민해보겠습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/domain/src/main/java/org/sopt/domain/repo/AuthRepository.kt
> +    suspend fun getUserinfo(): Result<Member?>
성공시에는 null로 떨어지는 경우는 없습니다. null타입은 허용하지 않고 에러로 래핑하는 방식으로 다시 구현해보겠습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/model/src/main/java/org/sopt/model/ValidateResult.kt
> +fun getResult(isValid: Boolean) = if (isValid) ValidateResult.Success else ValidateResult.Error
아 맞습니다 ! 클래스 내 함수로 구현 하는 편이 나을 것 같습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/network/src/main/java/org/sopt/network/di/ApiModule.kt
> +        retrofit.create(ReqresApi::class.java)
와 처음 알았습니다 ! 감사드립니다 !

2024-05-08 04:10 UTC, Sangwook123 commented on core/network/src/main/java/org/sopt/network/interceptor/AuthInterceptor.kt
> +        runBlocking { if (memberId != null) userPreferencesDataSource.setMemberId(memberId) }
넵 Location키에 memberId가 담겨서 내려옵니다

2024-05-08 04:10 UTC, Sangwook123 commented on core/network/src/main/java/org/sopt/network/interceptor/AuthInterceptor.kt
> +        ).addHeader("Accept-Encoding", "identity").build()
디버깅을 위해서 작성해두었다가 지우질 못했습니다. 수정 하겠습니다

2024-05-08 04:10 UTC, Sangwook123 commented on core/network/src/main/java/org/sopt/network/model/response/base/ApiError.kt
> +)
감사합니다 ! custom Exception 활용해서 에러처리를 하면 보다 여러 상황에 유연하게 대응할 수 있을 것 같습니다! 적용해보겠습니다 !

2024-05-08 04:10 UTC, Sangwook123 commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +    val userState: StateFlow<PagingData<ReqresUser>> = _userState.asStateFlow()
데이터 홀더의 역할을 하기 위해서 stateFlow로 저장해 두었습니다만, 컴포저블 함수 내 collectAsLazyPagingItems()에서 이미 데이터 홀더의 역할을 해주고있기 때문에, StateFlow로 저장할 필요 없이 바로 Flow를 활용해도 될 것 같습니다.

2024-05-08 04:10 UTC, Sangwook123 commented on core/data/build.gradle.kts
> +    implementation(libs.androidx.paging)
잘못 작성한 것 같습니다. 수정 하겠습니다 !

2024-05-08 04:10 UTC, Sangwook123 commented on feature/mypage/src/main/java/org/sopt/mypage/modifypassword/ModifyPasswordViewModel.kt
> +                }
음 status 코드에 따른 처리는 뷰모델에서 일어나야할 로직은 아닌 것 같습니다. data단에서 처리 후 필요한 정보만 뷰모델에서 사용하는 방식으로 수정해보겠습니다.

2024-05-08 04:32 UTC, Sangwook123 commented on feature/main/src/main/java/org/sopt/main/navigator/MainScreen.kt
> +                                launchSingleTop = true
스택에 지정된 화면이 최대 1개까지만 존재하도록 합니다 !

2024-05-08 04:38 UTC, Sangwook123 commented on core/datastore/src/main/java/org/sopt/datastore/source/UserPreferencesDataSource.kt
>      suspend fun setUserData(user: UserData) {
넵 필요한 부분만 변경하기 위해 copy를 사용합니다.

2024-05-10 10:23 UTC, l2hyunwoo requested changes
고생많으셨습니다. 엄청 빠르게 많은 부분을 잘 반영하셨네요ㅋㅋ 고생하셨습니다.

2024-05-10 10:23 UTC, l2hyunwoo commented on feature/home/src/main/java/org/sopt/home/HomeViewModel.kt
> +        userRepository.getUser().distinctUntilChanged().cachedIn(viewModelScope)
distinctUntilChanged 붙인 이유가 있을까요?

2024-05-10 10:23 UTC, l2hyunwoo approved these changes
Approve인데 잘못남겼어요! 고생하셨습니다. LGTM 👍🏻

2024-05-24 11:40 UTC, merged